/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontSize: {
        '2xs': ['10px', '15px'],
      },
      colors: {
        theme: {
          bg: 'var(--color-bg)',
          surface: 'var(--color-surface)',
          border: 'var(--color-border)',
          'border-control': 'var(--color-border-control)',
          text: 'var(--color-text)',
          muted: 'var(--color-muted)',
          'muted-on-bg': 'var(--color-muted-on-bg)',
          primary: 'var(--color-primary)',
          'primary-hover': 'var(--color-primary-hover)',
          'primary-tint': 'var(--color-primary-tint)',
          'on-primary': 'var(--color-on-primary)',
          critical: 'var(--color-critical)',
          'critical-bg': 'var(--color-critical-bg)',
          'critical-text': 'var(--color-critical-text)',
          'warning-bg': 'var(--color-warning-bg)',
          'warning-text': 'var(--color-warning-text)',
          'healthy-bg': 'var(--color-healthy-bg)',
          'healthy-text': 'var(--color-healthy-text)',
          'row-critical': 'var(--color-row-critical)',
          'row-warning': 'var(--color-row-warning)',
        },
        medex: {
          bg: 'var(--color-bg)',
          sidebar: 'var(--color-surface)',
          topbar: 'var(--color-surface)',
          surface: 'var(--color-surface)',
          elevated: 'var(--color-surface)',
          hover: 'rgba(15, 118, 110, 0.06)',
          border: 'var(--color-border)',
          'border-subtle': 'var(--color-border)',
          'border-active': 'var(--color-border-control)',
          primary: 'var(--color-text)',
          secondary: 'var(--color-muted)',
          muted: 'var(--color-muted)',
          disabled: 'var(--color-border-control)',
          cyan: {
            DEFAULT: 'var(--color-primary)',
            light: 'var(--color-primary)',
            glow: 'rgba(130, 168, 144, 0.2)',
          },
          sage: {
            DEFAULT: 'var(--color-primary)',
            light: '#a3c4b0',
            dark: '#2d4d38',
            glow: 'rgba(130, 168, 144, 0.25)',
          },
          ochre: {
            DEFAULT: 'var(--color-warning-text)',
            light: '#f5b759',
            dark: '#8c4f0b',
            glow: 'rgba(224, 159, 62, 0.25)',
          },
          red: {
            DEFAULT: 'var(--color-critical)',
            light: 'var(--color-critical-text)',
            glow: 'rgba(220, 38, 38, 0.15)',
          },
          amber: {
            DEFAULT: 'var(--color-warning-text)',
            light: 'var(--color-warning-text)',
            glow: 'rgba(224, 159, 62, 0.2)',
          },
          green: {
            DEFAULT: 'var(--color-healthy-text)',
            light: 'var(--color-healthy-text)',
            glow: 'rgba(116, 198, 157, 0.2)',
          },
        },
        palette: {
          lime: '#82a890',
          coffee: '#090e0c',
          'coffee-surface': '#111a16',
          'coffee-card': '#18241f',
          porcelain: '#F0F7F3',
          beige: '#889e93',
          'beige-muted': '#53695d',
          flame: '#FF807B',
          'flame-hover': '#FF9A91',
          'flame-tint': 'rgba(255, 128, 123, 0.15)',
          'lime-tint': 'rgba(130, 168, 144, 0.18)',
        },
      },
      fontFamily: {
        sans: [
          'DM Sans',
          'sans-serif',
        ],
        display: ['Space Grotesk', 'sans-serif'],
        mono: ['IBM Plex Mono', 'monospace'],
      },
    },
  },
  plugins: [],
};
