/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        theme: {
          bg: 'var(--color-bg)',
          surface: 'var(--color-surface)',
          border: 'var(--color-border)',
          'border-control': 'var(--color-border-control)',
          text: 'var(--color-text)',
          muted: 'var(--color-muted)',
          'muted-on-bg': 'var(--color-muted-on-bg)',
          primary: 'var(--color-primary)',
          'primary-hover': 'var(--color-primary-hover)',
          'primary-tint': 'var(--color-primary-tint)',
          'on-primary': 'var(--color-on-primary)',
          critical: 'var(--color-critical)',
          'critical-bg': 'var(--color-critical-bg)',
          'critical-text': 'var(--color-critical-text)',
          'warning-bg': 'var(--color-warning-bg)',
          'warning-text': 'var(--color-warning-text)',
          'healthy-bg': 'var(--color-healthy-bg)',
          'healthy-text': 'var(--color-healthy-text)',
          'row-critical': 'var(--color-row-critical)',
          'row-warning': 'var(--color-row-warning)',
        },
        medex: {
          bg: 'var(--color-bg)',
          sidebar: 'var(--color-surface)',
          topbar: 'var(--color-surface)',
          surface: 'var(--color-surface)',
          elevated: 'var(--color-surface)',
          hover: 'rgba(15, 118, 110, 0.06)',
          border: 'var(--color-border)',
          'border-subtle': 'var(--color-border)',
          'border-active': 'var(--color-border-control)',
          primary: 'var(--color-text)',
          secondary: 'var(--color-muted)',
          muted: 'var(--color-muted)',
          disabled: 'var(--color-border-control)',
          cyan: {
            DEFAULT: 'var(--color-primary)',
            light: 'var(--color-primary)',
            glow: 'rgba(45, 212, 191, 0.15)',
          },
          red: {
            DEFAULT: 'var(--color-critical)',
            light: 'var(--color-critical-text)',
            glow: 'rgba(220, 38, 38, 0.15)',
          },
          amber: {
            DEFAULT: 'var(--color-warning-text)',
            light: 'var(--color-warning-text)',
            glow: 'rgba(245, 158, 11, 0.15)',
          },
          green: {
            DEFAULT: 'var(--color-healthy-text)',
            light: 'var(--color-healthy-text)',
            glow: 'rgba(16, 185, 129, 0.15)',
          },
        },
        palette: {
          lime: '#C5D86D',
          coffee: '#261C15',
          'coffee-surface': '#33261D',
          'coffee-card': '#3D2F24',
          porcelain: '#F7F7F2',
          beige: '#E4E6C3',
          'beige-muted': '#D3D6AC',
          flame: '#F05D23',
          'flame-hover': '#D94C15',
          'flame-tint': 'rgba(240, 93, 35, 0.15)',
          'lime-tint': 'rgba(197, 216, 109, 0.15)',
        },
      },
      fontFamily: {
        sans: [
          'Plus Jakarta Sans',
          'Inter',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'sans-serif',
        ],
        mono: ['JetBrains Mono', 'SF Mono', 'Menlo', 'monospace'],
      },
    },
  },
  plugins: [],
};
