import React from 'react';
import { PageHeader } from '../components/common/PageHeader';
import { SectionCard } from '../components/common/SectionCard';
import { StatusBadge } from '../components/common/StatusBadge';
import { PriorityBadge } from '../components/common/PriorityBadge';
import { Check, Edit2, X, ArrowUpRight, Cpu } from 'lucide-react';

export const TransferView: React.FC = () => {
  return (
    <div className="space-y-6">
      <PageHeader
        title="Redistribution & Transfer Review"
        subtitle="Ranked redistribution proposals generated by Google OR-Tools optimization solver with Human-in-the-Loop decision governance."
        badge={<StatusBadge status="CYAN" label="POST /optimize" />}
        breadcrumbs={[
          { label: 'MEDEx' },
          { label: 'Redistribution' },
        ]}
      />

      {/* Optimizer Trigger Bar */}
      <div className="medex-panel p-4 flex flex-wrap items-center justify-between gap-4 bg-medex-surface/60">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-md bg-medex-cyan/15 text-medex-cyan">
            <Cpu className="w-5 h-5" />
          </div>
          <div>
            <h4 className="text-xs font-semibold text-medex-primary">
              OR-Tools Transportation Optimizer
            </h4>
            <p className="text-2xs text-medex-secondary">
              Ensures donor maintains ≥14 days cover, batch expiry &gt; transit, vehicle capacity.
            </p>
          </div>
        </div>

        <button
          type="button"
          className="px-3.5 py-1.5 rounded-md bg-medex-cyan text-medex-bg font-semibold text-xs opacity-60 cursor-not-allowed inline-flex items-center gap-1.5"
        >
          <Cpu className="w-3.5 h-3.5" />
          <span>Run Optimizer (Feature Phase 2)</span>
        </button>
      </div>

      {/* Sample Transfer Proposal Card Shell */}
      <SectionCard
        title="Ranked Proposals (OPEN State)"
        subtitle="Select a proposal to review, approve, modify, reject, or escalate"
        actionSlot={
          <span className="text-2xs font-mono text-medex-muted">
            GET /transfers
          </span>
        }
      >
        <div className="medex-panel p-4 border-medex-cyan/30 bg-medex-surface/40 space-y-4">
          <div className="flex flex-wrap items-center justify-between gap-2 pb-3 border-b border-medex-border">
            <div className="flex items-center gap-2">
              <PriorityBadge score={0.94} label="Rank #1" />
              <span className="text-xs font-bold text-medex-primary font-mono">
                Transfer T-001
              </span>
              <StatusBadge status="CYAN" label="OPEN" />
            </div>

            <div className="flex items-center gap-2">
              <button
                type="button"
                className="px-2.5 py-1 rounded bg-medex-green/15 border border-medex-green/40 text-medex-green-light text-2xs font-semibold inline-flex items-center gap-1 opacity-70 cursor-not-allowed"
              >
                <Check className="w-3 h-3" />
                <span>APPROVE</span>
              </button>
              <button
                type="button"
                className="px-2.5 py-1 rounded bg-medex-amber/15 border border-medex-amber/40 text-medex-amber-light text-2xs font-semibold inline-flex items-center gap-1 opacity-70 cursor-not-allowed"
              >
                <Edit2 className="w-3 h-3" />
                <span>MODIFY</span>
              </button>
              <button
                type="button"
                className="px-2.5 py-1 rounded bg-medex-red/15 border border-medex-red/40 text-medex-red-light text-2xs font-semibold inline-flex items-center gap-1 opacity-70 cursor-not-allowed"
              >
                <X className="w-3 h-3" />
                <span>REJECT</span>
              </button>
              <button
                type="button"
                className="px-2.5 py-1 rounded bg-medex-surface border border-medex-border text-medex-secondary text-2xs font-semibold inline-flex items-center gap-1 opacity-70 cursor-not-allowed"
              >
                <ArrowUpRight className="w-3 h-3" />
                <span>ESCALATE</span>
              </button>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs font-sans">
            <div className="p-3 rounded bg-medex-surface border border-medex-border">
              <span className="text-2xs font-mono text-medex-muted uppercase block">
                DONOR FACILITY (FROM)
              </span>
              <span className="font-semibold text-medex-primary block mt-0.5">
                CHC Sample-003 (Block-A)
              </span>
              <span className="text-2xs text-medex-secondary font-mono mt-1 block">
                Cover before: 42 days &rarr; Cover after move: 16 days (Buffer OK &ge;14d)
              </span>
            </div>

            <div className="p-3 rounded bg-medex-surface border border-medex-border">
              <span className="text-2xs font-mono text-medex-muted uppercase block">
                RECIPIENT FACILITY (TO)
              </span>
              <span className="font-semibold text-medex-primary block mt-0.5">
                PHC Sample-014 (Block-A)
              </span>
              <span className="text-2xs text-medex-secondary font-mono mt-1 block">
                Cover before: 5.1 days (RED) &rarr; Cover after move: 21 days (GREEN)
              </span>
            </div>
          </div>

          <div className="p-3 bg-medex-elevated rounded border border-medex-border text-2xs font-sans text-medex-secondary">
            <span className="font-semibold text-medex-cyan block font-mono mb-0.5">
              GEMINI EXPLANATION:
            </span>
            "TN-CHC-003 holds 42 days of ORS and retains 16 days after dispatch. The recipient PHC is flood-prone and reaches 21 days of cover."
          </div>
        </div>
      </SectionCard>
    </div>
  );
};
